"""Static configuration for the Digital Paani take-home ingestion pipeline."""

SHEET_CONFIG = {
    "plant_design": {"header": 2, "usecols": "B:L"},
    "water quality": {"header": 3, "usecols": "C:P"},
    "water_balance": {"header": 2, "usecols": "A:S"},
    "site-characteristics": {"header": 5, "usecols": "D:L"},
    "process_design": {"header": 4, "usecols": "B:L"},
}

EXPECTED_ROWS_PER_SHEET = 6

PLANT_REQUIRED_FIELDS = {
    "client_name",
    "sector",
    "location_type",
    "design_flow_kld",
    "mean_flow_kld",
    "peak_flow_kld",
    "unit_processes",
    "pfd_pfd_displayed",
    "freshwater_source",
    "wastewater_source",
    "wastewater_destination",
    "water_balance_displayed",
}

TANK_REQUIRED_FIELDS = {
    "tank_count",
    "tank_arrangement",
    "tank_shape",
    "covered",
    "tank_condition",
    "tank_accessibility",
    "sludge_observed_in_tank",
}

ENUMS = {
    "sector": {
        "municipal",
        "industrial",
        "buildings: commercial",
        "buildings: residential",
    },
    "location_type": {"Basement", "Ground level"},
    "unit_processes": {
        "ACTIVATED_SLUDGE",
        "ANOXIC_TREATMENT",
        "BELT_FILTER_PRESS_DEWATERING",
        "BRINE_CONCENTRATION",
        "CARTRIDGE_FILTRATION",
        "CASCADE_AERATION",
        "CASS",
        "CENTRIFUGE_DEWATERING",
        "CENTRIFUGE_THICKENING",
        "CHLORINATION",
        "CLARIFICATION",
        "COLLECTION",
        "COOLING",
        "CRYSTALLIZATION",
        "DAF_THICKENING",
        "DECHLORINATION",
        "DISSOLVED_AIR_FLOTATION",
        "DISTRIBUTION",
        "EQUALIZATION",
        "FILTER_FEED",
        "FINE_SCREENING",
        "GRAVITY_BELT_THICKENING",
        "GRAVITY_THICKENING",
        "GRIT_REMOVAL",
        "IRRIGATION",
        "MBBR",
        "MBR",
        "MEDIA_FILTRATION",
        "MICROFILTRATION",
        "NANOFILTRATION",
        "OIL_GREASE_REMOVAL",
        "OZONATION",
        "PLATE_FRAME_FILTRATION",
        "RO_DESALINATION",
        "ROTARY_DRUM_SCREENING",
        "ROTARY_DRUM_THICKENING",
        "SABRE",
        "SBR",
        "SCREENING",
        "SCREW_PRESS_DEWATERING",
        "SLUDGE_DIGESTION",
        "SLUDGE_HOLDING",
        "SLUDGE_TRANSFER",
        "SOFTENING",
        "SOLAR_DRYING",
        "SUMP",
        "THERMAL_DRYING",
        "TREATED_WATER",
        "TUBE_SETTLING",
        "ULTRAFILTRATION",
        "UV_DISINFECTION",
    },
    "freshwater_source": {"Borewell", "Municipal", "Surface", "Tankers", "Other"},
    "wastewater_source": {
        "Domestic sewage",
        "Kitchen/canteen",
        "Laundry",
        "Municipal sewage",
        "Industrial effluent",
        "Combined effluent (CETP)",
        "Cooling tower blowdown",
        "Boiler blowdown",
        "RO reject",
        "Wash water",
        "Stormwater",
        "Sump",
        "Other",
    },
    "wastewater_destination": {
        "On-site reuse",
        "Surface water discharge",
        "Sewer discharge",
        "Groundwater recharge",
        "Land application/irrigation",
        "Tanker removal",
        "Zero liquid discharge (ZLD)",
        "Other",
    },
    "tank_shape": {"Rectangular", "Cylindrical"},
    "covered": {"Open", "Covered", "Sealed/Closed"},
    "tank_condition": {"Good", "Fair", "Poor"},
    "tank_accessibility": {"Easy", "Restricted", "Unsafe"},
}

# Plausibility ranges from design_data_fields.md / validation_rules.md.
# Tuples are inclusive lower/upper bounds. None means no bound on that side.
BOUNDS = {
    "inlet_cod_mg_l": (300.0, 1000.0),
    "inlet_bod_mg_l": (100.0, 600.0),
    "inlet_n_mg_l": (10.0, 100.0),
    "inlet_tss_mg_l": (100.0, 500.0),
    "inlet_ph": (1.0, 14.0),
    "outlet_cod_mg_l": (22.5, 82.5),
    "outlet_bod_mg_l": (4.5, 22.0),
    "outlet_n_mg_l": (0.9, 11.0),
    "outlet_tss_mg_l": (9.0, 33.0),
    "freshwater_tds_mg_l": (45.0, 275.0),
    "freshwater_ph": (0.0, 14.0),
    "freshwater_hardness_mg_l": (9.0, 198.0),
    "freshwater_fluoride_mg_l": (0.009, 0.33),
    "treated_water_reuse_fraction": (0.0, 1.0),
    "reuse_water_quality_tds_mg_l": (450.0, 1100.0),
}

# Rules that explicitly say zero or negative is a problem.
STRICTLY_POSITIVE_FIELDS = {
    "design_flow_kld",
    "mean_flow_kld",
    "peak_flow_kld",
    "freshwater_cost_per_kl",
    "consumption_domestic_kld",
    "consumption_laundry_kld",
    "consumption_kitchen_kld",
    "reuse_flushing_kld",
    "reuse_gardening_kld",
    "reuse_cooling_tower_kld",
    "tank_count",
    "tank_length_m",
    "tank_width_m",
    "tank_diameter_m",
    "tank_height_m",
    "wiring_distance_to_panel_m",
}

# Schema says tank volume is non-negative. Missing is allowed; negative is not.
NONNEGATIVE_FIELDS = {"tank_volume_m3"}
